# Use root/example as user/password credentials
version: '3.1'

services:
   app:
      image: todoapp
      networks:
        - my-network
      depends_on:
        - mysql
   mysql:
     image: mysql:5.6
     networks:
        - my-network
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: db_example
       MYSQL_USER: user
       MYSQL_PASSWORD: password
networks:
  my-network:
    driver: bridge
  