# Use root/example as user/password credentials
version: "3.9"

services:
   app:
     image: todoapp
     deploy:
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3
         window: 200s
     ports:
       - 80:8080
     networks:
       - my-network     
     depends_on:
       - mysqldb
   mysqldb:
     image: mysql:5.6
     networks:
       - my-network
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: db_example
       MYSQL_USER: user
       MYSQL_PASSWORD: password
     ports:
       - 3306:3306
       
networks:
  my-network:
    driver: bridge
  